
//This data must be in order from oldest date to newest, otherwise it looks weird... so yeah//
//use this to make a new paragraph in content:  <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  //
var data2 = [
    {"id": "1", "title": "Launch of the Website!",          "date": "1/26/23", "link": "", "splash": "Time to celebrate, where's the champagne?", "author": "The_: Team",
    "content": "Here it is the launch day of the Acheson Athletics website. By no means has it been easy to get to this stage. But like the quote says  it's about the journey not the destination. Through the tedious ups and downs from getting the site to deploy live to the internet, to failing on getting the database into a functional state. I think the journey has taught me more than any class could teach me alone. I know our team lacked some skill in departments in developing the full scope of the project, but we didn't lack the ability to keep trying. Even in the face of constant adversity and roadblocks halting progress of the website, Thomas, Bu, Kyle and I never gave up. That's what I am most proud of on this special day. -Zeke Qurnones, Project Manager <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Finally, it's what you've been waiting for, Acheson Athletics website is finally launching. It has been a journey. The team begins with limited knowledge of code and database. However, we learn as we go. I am proud to say that we have learned a lot and are able to present you with the website. There are still some areas that we lacked but we are also improving each day. - Bu Meh, UI/UX Designer <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; It's finally here after long last! This project has definitely had its ups and downs, but I couldn't be prouder of our team here at The_:. Although we have had to drastically reduce our scale, especially in the ''user account'' oriented features, I think we ended up pulling through with a pretty feature-packed website. Bu and Zeke worked tremendously hard to get the user database in a functional state the entire development period, and that alone I think requires commendation. Kyle was a great team member, always asking the important questions, and building a robust badge system, even if it isn't fully implemented into the database as of writing. Blaine, our project sponsor, also put a tremendous amount of leg-work in, writing 90% of all scripts used in our videos and being the star of the show. Overall, I couldn't ask for a better team. -Thomas Avinger, Software Engineer <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hi I'm Kyle I helped with setting up the database and worked on the badge system for the website. There has been a lot of adversity our team had endured in the making of this project. It took a while to get everything we needed to get our website online but now we've finally arrived and now we have a product that we're pleased to show you today. We have a totally unique product that is not been implemented before. Something that our team can proudly look at with pride that shows our creativity, and unique problem solving skills to make a new project that will improve the lives of our customers. -Kyle Longaker, Web Developer"},

    {"id": "2", "title": "New Feature: Category Buttons",   "date": "3/30/23", "link": "", "splash": "Try them out on your next visit to the videos page", "author": "Thomas Avinger, Web Developer",
    "content": "Hello! Its me again here to rant about how this took longer than it should have. Regardless, I'm glad that the end result turned out to be a perfect copy of my vision. Shoutout to Zeke for reccomending this feature to be implemented. The page definitely needed a function like this, especially as our video catalog grows in size over our website's lifespan. Okay, lets talk about how to use them! They're pretty simple. Each button correlates with a muscle category. Click the button that correlates with the category you want to see. The page will reload, only showing those videos. You can also click the ''Video Catalog'' button at the top to reset the page to show all videos again. Ok, that's all for now. I'll let you know when I add more buttons to the site."},

    {"id": "3", "title": "New Video: Romanian Deadlifts",   "date": "4/5/23", "link": "", "splash": "A great workout for your hamstrings", "author": "Thomas Avinger, Video Producer",
    "content": "A new video for the Legs category is out now! Watch the Romanian Deadlifts video today!"},

    {"id": "4", "title": "New Video: Crunches",             "date": "4/5/23", "link": "", "splash": "Refresh your memory on crunches with this video", "author": "Thomas Avinger, Video Producer",
    "content": "A new video for the Core category is out now! Watch the Crunches video today!"},
    {"id": "5", "title": "Update: New Videos",               "date": "6/15/23", "link": "", "splash": "8 new videos for your viewing pleasure", "author": "Thomas Avinger, Video Producer",
    "content": "Hello all, I've finally wrapped up all of the footage that Blaine and I recorded months ago and they are now fully edited for your viewing pleasure. <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The new videos include: <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Introduction to Legs <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Introduction to Core <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Chin-Ups <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Pull-Ups <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Deadlifts <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Squats <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Leg-Raises <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Oblique Crunches <br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  The inclusion of these 8 videos makes it 20 videos in total on the website. Unfortunately, this most likely marks the end of production, as the team and I look towards new projects. Please continue to enjoy the website and its content, as the site will remain up until further notice. Thank you for your support!"}
];